In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, classification_report, precision_recall_fscore_support
from sklearn.model_selection import KFold
import string

In [2]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import  LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report
import pickle

In [3]:
data = pd.read_csv('allNews.csv')

In [4]:
def tokenize(data , result):
    for i in range(len(data)):
        result[i] = word_tokenize(data['news'][i])

In [5]:
tokenize_text = {}

In [ ]:
tokenize(data , tokenize_text)

In [6]:
punctuation = word_tokenize(string.punctuation)

In [7]:
def punctuationFilter(data , punctuation , result):
    for i in range(len(data)):
        result[i] = [w for w in data[i] if not w in punctuation ]

In [8]:
punctuation_filtered_data = {}

In [9]:
punctuationFilter(tokenize_text , punctuation , punctuation_filtered_data)

In [13]:
final_data = {'news':punctuation_filtered_data , 'label':data['label']}

In [14]:
cleanedNewsData = pd.DataFrame(final_data)

In [16]:
cleanedNewsData.to_csv('cleanedNewsData.csv')

# CLASSIFICATION

In [3]:
data = pd.read_csv('cleanedNewsData.csv')

In [4]:
data.head()

Unnamed: 0                                               news label
0           0  ['Daniel', 'Greenfield', 'a', 'Shillman', 'Jou...  FAKE
1           1  ['Google', 'Pinterest', 'Digg', 'Linkedin', 'R...  FAKE
2           2  ['U.S.', 'Secretary', 'of', 'State', 'John', '...  REAL
3           3  ['—', 'Kaydee', 'King', 'KaydeeKing', 'Novembe...  FAKE
4           4  ['It', "'s", 'primary', 'day', 'in', 'New', 'Y...  REAL

In [5]:
x_train,x_test,y_train,y_test = train_test_split(data['news'] , data['label'] , test_size = 0.01 , random_state = 7)

In [6]:
tfidf = TfidfVectorizer(ngram_range=(1,2),use_idf=True,smooth_idf=True)

In [7]:
svm = Pipeline([
        ('svm_tfidf',tfidf),
        ('svm_clf',LinearSVC())
        ])

In [8]:
svm.fit(x_train , y_train)

Pipeline(memory=None,
         steps=[('svm_tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 2), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('svm_clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
       

In [21]:
svm_y_pred = svm.predict(x_test)

In [22]:
len(svm_y_pred)

66

In [15]:
print(accuracy_score(y_test , svm_y_pred))

0.9393939393939394


In [20]:
print(confusion_matrix(svm.predict(x_test), y_test))

[[26  2  0]
 [ 2 32  0]
 [ 0  0  4]]


In [17]:
print(classification_report(y_test, svm_y_pred))

              precision    recall  f1-score   support

        FAKE       0.93      0.93      0.93        28
        REAL       0.94      0.94      0.94        34
        True       1.00      1.00      1.00         4

    accuracy                           0.94        66
   macro avg       0.96      0.96      0.96        66
weighted avg       0.94      0.94      0.94        66



In [ ]:
model = 'classification_model.sav'

In [45]:
pickle.dump(svm , open(model , 'wb'))

In [3]:
real_news_list = []

In [4]:
for i in range(2,10):
    real_news_list.append([x['news'][i]])

In [7]:
real_news_list[0]

['UNITED NATIONS: India has co-sponsored a UN General Assembly resolution that called for a fair, transparent and equitable access to essential medical supplies and any future vaccines developed to fight Covid-19 that has claimed over 177,000 lives and infected more than 2.5 million people. The 193-Member General Assembly adopted the Mexico-drafted resolution \'International cooperation to ensure global access to medicines, vaccines and medical equipment to face Covid-19\' by consensus on Monday. Pakistan was among the small minority of nations that did not sponsor the resolution. India was among the 179 nations co-sponsoring the resolution that called for ensuring "fair, transparent, equitable, efficient and timely access to and distribution of preventive tools, laboratory testing, reagents and supporting materials, essential medical supplies, new diagnostics, drugs and future Covid-19 vaccines" to all nations, particular developing countries. "India has proactively engaged in support